### ISSUE TITLE
ROADMAP

### ISSUE THREAD

**Issue by Symbian9** [sk1project/sk1-wx#45]
# ROADMAP (update it)
* sK1 2.0rc1
  * [x] rewrite sK1 0.xx to wxPython
  * [x] SK2 format specification
  * ...
* sK1 2.0rc2
  * [x] SK & SK1 import/export
  * ...
* sK1 2.0rc3
  * [x] SVG import/export 
  * ...
* sK1 2.0rc4
  * [ ] task 1
  * [ ] task 2
  * [ ] task 3
    * [ ] sub-task
    * ...
* sK1 2.0 (release)
* ...
## Wiki page
* https://github.com/sk1project/sk1-wx/wiki/ROADMAP

**Comment by Kliurka** [comment]
Please add tool for adjust space between letters and words

**Comment by sk1project** [comment]
Milestones have been added for issues here
