### ISSUE TITLE
Setup Travis CI for auto-build AppImage (portable binary packages for Linux)

### ISSUE THREAD

**Issue by Symbian9** [sk1project/sk1-wx#86]
Propose setup `master` branch to produce auto-builds using Travis CI as `*.AppImage` package -- universal portable package format for most of Linux distributions.

* http://github.com/AppImage/AppImageKit
  * https://github.com/probonopd/linuxdeployqt
  * https://github.com/probonopd/uploadtool

Firstly, you need setup `.travis.yml` script in the root of `master` branch, for example:

* https://github.com/probonopd/linuxdeployqt/blob/master/.travis.yml
* https://github.com/leozide/leocad/blob/master/.travis.yml
* https://github.com/Symbian9/azpainter/blob/master/.travis.yml

P.S.: Known apps that already provide AppImage's listed on *AppImageHub*

* https://appimage.github.io/apps

### TODO

- [x] Create `.travis.yml` (initial commit) https://github.com/sk1project/sk1-wx/pull/64
- [ ] Setup `.travis.yml` for AppImage
  - [ ] Setup builds dependency
  - [ ] Setup builds deploy to Trash.sh & to `continuous` release on Github  
  - [ ] Other settings

### NOTE

@probonopd, I'm a collaborator in `sk1-wx` project specially for AppImage task solving, so here I will ask You mostly for help me to setup this project for sK1-2.x-*.AppImage`. This is WIP issue.

**Comment by probonopd** [comment]
Please see https://github.com/sk1project/sk1-wx/pull/212 for AppImage.
